# 线程池异常处理

线程池中异常的处理有如下几种:

1. 在 run() 方法中添加 `try-catch`
2. 实现 `UncaughtExceptionHandler` 接口，并调用 Thread 对象的 `setUncaughtExceptionHandler(UncaughtException eh)` 方法。通过 ThreadFactory 控制线程的创建。创建线程池时，传递 ThreadFactory 即可。ThreadFactory 是一个接口，只有一个 `Thread newThread(Runnable r)` 方法，我们可以手动实现该接口，也可以使用 Apache Commons、Google Guava 等工具类库为我们创建 ThreadFactory
3. 通过 `Thread.setDefaultUncaughtExceptionHandler(UncaughtException eh)` 设置一个全部线程共享的异常处理器
4. ThreadGroup 类实现了 `UncaughtExceptionHandler` 接口，通过 ThreadGroup 可以为一组线程设置异常处理器

```java
Thread t = new Thread(() -> System.out.println(1 / 0));
t.start();
```

该代码抛出的异常就是通过 ThreadGroup 进行处理:

```java
public void uncaughtException(Thread t, Throwable e) {  
    if (parent != null) {  
        parent.uncaughtException(t, e);  
    } else {  
        Thread.UncaughtExceptionHandler ueh =  
            Thread.getDefaultUncaughtExceptionHandler();  
        if (ueh != null) {  
            ueh.uncaughtException(t, e);  
        } else if (!(e instanceof ThreadDeath)) {  
	        // 上述代码抛出异常时，执行该处的逻辑
            System.err.print("Exception in thread \""  
                             + t.getName() + "\" ");  
            e.printStackTrace(System.err);  
        }  
    }  
}
```

# UncaughtExceptionHandler 一定会执行吗？

答案是否定的，当使用 `submit()` 方法执行任务时，该方法的代码逻辑会帮我们捕获异常，因此即使代码中发生异常，
UncaughtExceptionHandler 也不会被执行。如果要知道 `sumbmit()` 提交的任务的执行情况，则需要调用 `Future.get()` 方法进行判断

使用 `execute()` 方法执行任务时，如果代码中抛出异常，UncaughtExceptionHandler 的处理逻辑会被执行

```ad-info
title: 总结

UncaughtExceptionHandler 只对 execute() 方法起作用，对 submit() 方法不起作用
```

# UncaughtExceptionHandler 是适合在线程池中使用？

答案是不适合。虽然通过设置 `UncaughtExceptionHandler` 可以设置统一的异常处理，避免了重复使用 `try-catch`，但是在将异常交给 `UncaughtExceptionHandler` 处理的时候，对应的工作线程会因为异常而退出，从而导致线程池频繁的创建新的线程来进行补充，这违背了线程池重复利用已创建线程的初衷，同时线程池的效率也会下降很多。

# ScheduledThreadPoolExecutor 异常的处理

`ScheduledThreadPoolExecutor` 用来封装任务的是 `ScheduledFutureTask`。`ScheduledFutureTask` 是 `FutureTask` 的子类，所以可以通过 `Future.get()` 方法获取到结果和异常。

在使用 `ThreadPoolExecutor.submit` 和 `ScheduledThreadPoolExecutor.schedule` 方法时，可以通过 `Future.get()` 方法获取到结果和异常。但是，对于 `ScheduledThreadPoolExecutor.scheduleWithFixedDelay` 和 `scheduleAtFixedRate` 这两个方法，其返回值 `Future` 只能够用来取消任务，而不能得到运行结果和异常。因为这两个方法执行的是定时任务，是反复执行的。因此，对于这两个方法来说，在 `Runnable.run` 方法中加上 `try...catch` 是必须的，否则代码中出现异常了我们也不知道。同时如果这两个方法抛出异常，会将对应的任务挂起，不再执行。